---
- hosts: web 
  become: yes
  become_method: yes
  tasks:

  - name: stop smb service 
    service: 
      name: smb 
      state: stopped

  
  - name: uninstall samba
    yum: 
      name: samba
      state: absent

   
