---
- hosts: web
  tasks:

  - name: "samba file"
    debug:
      msg: "smb item: {{ item }}"
    with_items:
            - comment
            - path
            - public 
            - writable
            - browsable
